apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-two
  labels:
    app: my-app-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-two
  template:
    metadata:
      labels:
        app: my-app-two
    spec:
      imagePullSecrets:
        - name: my-registry-two
      containers:
        - name: my-app
          image: 423623856295.dkr.ecr.eu-central-1.amazonaws.com/my-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
